problem_title = "Even Fibonacci numbers"
problem_lines = [
    "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be",
    "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...",
    "By considering the terms in the Fibonacci sequence whose values do not exceed four milion, find the sum of the even-valued terms",
]


def problem_statement():
    print("Problem Statement:")
    print("\t", problem_title)

    for problem_line in problem_lines:
        print("\t\t", problem_line)

    print("\n\n")


def get_fibonacci(max):
    a = [1]
    new_val = 1
    while new_val < max:
        a.append(new_val)
        new_val = a[-1] + a[-2]
    return a


def sum_of_even(search_list):
    even_sum = 0
    for i in search_list:
        if (i % 2) == 0:
            even_sum += i
    return even_sum


def run():
    max_number = 4000000

    series = get_fibonacci(max_number)
    # print("The fibonacci series is", series)

    even_sum = sum_of_even(series)
    print("The sum of the even values terms of a fibonacci series whose values dont exceed four million is", even_sum)
